# Generated by Django 5.0.6 on 2025-01-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='path_qrcode',
            field=models.ImageField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
    ]
